### ISSUE TITLE
AUC=0.625

### ISSUE THREAD

**Issue by rtmaww** [tmliang/CGRE#1]
Hello. I ran the eval.py with pretrained model but got a AUC result=0.625, which is strange and different from the reported result=0.52. I wonder if there is something wrong with the evaluation codes?
![image](https://user-images.githubusercontent.com/32048818/124701088-851ab680-df20-11eb-9eca-caa626d0595c.png)

**Comment by tmliang** [comment]
Maybe you can try our published codes in [codeocean](https://codeocean.com/capsule/4267354/tree/v1), which can reproduce our results directly.
