### ISSUE TITLE
Constraint Graph has only 52 relation types

### ISSUE THREAD

**Issue by kartikeya-badola** [tmliang/CGRE#2]
Dear Author, 
The NYT dataset has 58 relation types (including NA) but the constraint graph provided here has only 52 relation types. What is the cause of such discrepancy? How do we figure out the entity type information of the remaining 5 relations?

**Comment by kartikeya-badola** [comment]
['/sports/sports_team_location/teams',
'/people/ethnicity/people',
'/business/company/industry',
'/business/company_shareholder/major_shareholder_of',
'/people/ethnicity/includes_groups',]

the following relation types are missing in the constraint graph

**Comment by tmliang** [comment]
Following most of the previous works, we use the NYT dataset preprocessed by [OpenNRE](https://github.com/thunlp/OpenNRE/tree/old_version), which contains merely 53 relations.

For the other relations, you can simply specify the type constraints based on their definition. For example, the subject and object types of '/people/ethnicity/people' are both 'PERSON', obviously. 
If the definition of a relation is unclear, you can count the co-occurrence frequency of the relation with each entity type in the training set. Assume that for '/sports/sports_team_location/teams', the frequencies of GPE, LOC, and other types as subjects are 60%, 30%, and 10%, respectively, then GPE and LOC can both be considered as the subject constraints on '/sports/sports_team_location/teams'.

**Comment by kartikeya-badola** [comment]
Thank you for your reply. It seems that the newer version of OpenNRE has changed its rel2id.txt, which now has 57+1 relation types. The link you have shared belongs to the old branch. It is quite odd how there is a discrepancy in one of the most important papers in this field (PCNN). Sadly such randomness continues with HRERE (containing 54+1), RECON (containing 57+1) and CGRE (containing 52+1).

Thank you for your recommendation for figuring out the entity types of the remaining relation types.
