### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects RDFLib Version: 5.0.0   and   EOFError: Ran out of input

### ISSUE THREAD

**Issue by songshulei** [tmliang/CGRE#3]
num_workers=4 Always have this problem, 0 is no problem, please ask if this is due to pickle.load module or file open not closed, define the class, etc., how to solve this problem?

**Comment by tmliang** [comment]
It may cause by running multiprocessing on Windows. For Windows, you should set num_workers=0.
