### ISSUE TITLE
Questions about experimental data

### ISSUE THREAD

**Issue by nwt-musicApplication** [tmliang/CGRE#6]
Dear Author,
May I ask if there is any correlation between the P@N values on NYT-570K in Tables 3 and 6 of your paper? I don't quite understand why there is some difference between the two.

**Comment by tmliang** [comment]
For Table 3, P@Ns are for the whole test set. For Table 5 or 6, P@Ns are for the three sub test sets. As for how to construct these three sub test sets, you can refer to the description in sec. 3.5.1 of our paper, or sec. 4.4 of [PCNN+ATT](https://aclanthology.org/P16-1200v2.pdf)

**Comment by nwt-musicApplication** [comment]
Thank you very, very much for your reply! wish you every success your scientific research~
